namespace XamlExtensions
{
    [default_interface]
    runtimeclass Add
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Double GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Double GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Double GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass GridLengthAdd
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Microsoft.UI.Xaml.GridLength value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Microsoft.UI.Xaml.GridLength value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass Neg
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Double GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Double GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass Multiply
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Double GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Double GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Double GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass Divide
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Double GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Double GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Double GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass Add3
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Double GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Double GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty CProperty{ get; };
        static Double GetC(Microsoft.UI.Xaml.DependencyObject target);
        static void SetC(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Double GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass Multiply3
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Double GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Double GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty CProperty{ get; };
        static Double GetC(Microsoft.UI.Xaml.DependencyObject target);
        static void SetC(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Double GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass GridLengthAdd3
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Microsoft.UI.Xaml.GridLength value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Microsoft.UI.Xaml.GridLength value);

        static Microsoft.UI.Xaml.DependencyProperty CProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetC(Microsoft.UI.Xaml.DependencyObject target);
        static void SetC(Microsoft.UI.Xaml.DependencyObject target, Microsoft.UI.Xaml.GridLength value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }

    [default_interface]
    runtimeclass GridLengthMultiply
    {
        static Microsoft.UI.Xaml.DependencyProperty AProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetA(Microsoft.UI.Xaml.DependencyObject target);
        static void SetA(Microsoft.UI.Xaml.DependencyObject target, Microsoft.UI.Xaml.GridLength value);

        static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
        static Double GetB(Microsoft.UI.Xaml.DependencyObject target);
        static void SetB(Microsoft.UI.Xaml.DependencyObject target, Double value);

        static Microsoft.UI.Xaml.DependencyProperty ResultProperty{ get; };
        static Microsoft.UI.Xaml.GridLength GetResult(Microsoft.UI.Xaml.DependencyObject target);
    }
}
